### ISSUE TITLE
No web page at http://localhost:3000/

### ISSUE THREAD

**Issue by jhsu802701** [FoodIsLifeBGP/banana-rails#114]
Here's what I see when I bring up docker-compose up and go to http://localhost:3000/

![localhosts_3000](https://user-images.githubusercontent.com/2992358/99885232-168b2180-2bf9-11eb-927a-6ea3cd06c9e2.png)

**Comment by pravalikarouthu** [comment]
This is the backend service only and you’re on the right path. This means you’re backend server has started successfully. Please let me know if you have any questions

**Comment by jhsu802701** [comment]
Are there any instructions on how to get the whole app working on our local machines?
